Fix vignette config
Asek3/sodium-1.12 pull request #43
Opened 2024-05-05 03:35 UTC by ZZZank

I made this PR because the "toggle vignette" config is not taking effect, and vignette is always being rendered. 

That's because Vintagium mixins into `net.minecraft.client.gui.GuiIngame` for vignette control, but there's another class that implements vignette rendering: `net.minecraftforge.client.GuiIngameForge`, and basically fully replaces `GuiIngame`. 

GuiIngameForge provides a convinent static config for vignette control, so we can directly hooks into forge config instead of using our own config. 

I'm not removing the original mixin because there can be some MAGIC mods that is somehow using vanilla overlay rendering, but a note is added to inform devs that this mixin can be totally useless.

2024-05-20 02:05 UTC, embeddedt requested changes
From what I can tell this will prevent the option from being saved to disk. I would just cancel the vignette render using the Forge event based on the value of the Sodium flag instead.

2024-05-20 15:26 UTC, ZZZank commented
> From what I can tell this will prevent the option from being saved to disk.

That's true. I added the option back and used mixin for rendering control. From my tests, configs are saved (and read) successfully. 

> I would just cancel the vignette render using the Forge event based on the value of the Sodium flag instead.

There seems to be no vignette related event, so I just mixin into the `if` statement that controls vignette rendering.

It's not providing a "thorough" control over vignette, disabling `GuiIngameForge.renderVigntte` can still force disable vignette rendering, despite of Vintagium options. That's because vanilla/forge will not change its value, and mods that do change it explicitly must be doing so for a reason.

2024-05-21 13:39 UTC, embeddedt approved these changes

2024-07-10 00:38 UTC, Asek3 commented
I missed it at this point, thanks for the note

2024-07-10 00:38 UTC, merged